spring.application.name=demo

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.vectorstore.mariadb.initialize-schema=true
