spring.application.name=demo

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.vectorstore.mariadb.initialize-schema=true

spring.ai.mcp.client.streamable-http.connections.product-order-server.url=http://localhost:8090

spring.ai.mcp.client.stdio.connections.date-time-server.command=java.exe
spring.ai.mcp.client.stdio.connections.date-time-server.args=-jar,D:/springai/support/datetimetool.jar

# 노션 MCP Server
spring.ai.mcp.client.stdio.connections.notion.command=npx.cmd
spring.ai.mcp.client.stdio.connections.notion.args=-y,@notionhq/notion-mcp-server
spring.ai.mcp.client.stdio.connections.notion.env.NOTION_TOKEN=${NOTION_TOKEN}



