spring.application.name=demo

# 표준입출력 MCP 활성화
spring.ai.mcp.server.stdio=true

# 콘솔 로그 출력을 막는다
logging.console.enabled=false
spring.main.banner-mode=off
spring.main.log-startup-info=false

# 콘솔 대신 파일로 로그를 출력하도록 설정
logging.file.name=./log/mcp-server-stdio.log




